### ISSUE TITLE
Vibration des rechten Controllers bei Berührung der buttons

### ISSUE THREAD

**Issue by loppitz** [4ahmns2122-VR/VRProjekt2122-LOppitz#18]
code funktioniert nicht wie er sollte

**Comment by smeerws** [comment]
Hier bitte angeben wo welcher code

**Comment by loppitz** [comment]
im script PickUp1:

private void Start()
    {
        xr = (XRController)GameObject.FindObjectOfType(typeof(XRController));
    }

    public void OnTriggerEnter(Collider other)
    {
        if (other.tag == "button") {
           
           // Debug.Log("buzz");
            xr.SendHapticImpulse(0.7f, 2f);

        }
