### ISSUE TITLE
right hand position

### ISSUE THREAD

**Issue by loppitz** [4ahmns2122-VR/VRProjekt2122-LOppitz#19]

**Comment by smeerws** [comment]
Hab es hergerichtet. Möchte es aber nicht pushen, da ich dir nix kaputt machen möchte. 

Also im XR Rig bei 
1) der Main Cam, positon und rotation reset auf 0,
2) Right Hand Parent BoxCollider und XR Controller ausschalten (Löschen).

**Comment by loppitz** [comment]
sorry hatte bis jetzt keine zeit! sollte ich den neuen build dann nochmal hochladen??

**Comment by loppitz** [comment]
![Screenshot (359)](https://user-images.githubusercontent.com/73108662/152579675-a0e6a18d-4df0-43d7-b21b-0c8ed7dbd7b2.png)
ich kann den neuen stand nicht pushen

**Comment by smeerws** [comment]
Du hast online was geänder was offline nicht da ist. Gelb rote
Fehlermeldung.

loppitz ***@***.***> schrieb am Fr., 4. Feb. 2022, 19:02:
