### ISSUE TITLE
Compiler Errors seit erstellen neuer Branch

### ISSUE THREAD

**Issue by loppitz** [4ahmns2122-VR/VRProjekt2122-LOppitz#3]
Play Modus funktioniert plötzlich nichtmehr

**Comment by smeerws** [comment]
![image](https://user-images.githubusercontent.com/28704310/150359051-f9168f92-7b97-4728-92f4-94dc49d6019d.png)

**Comment by smeerws** [comment]
go to Window-> Package Manager

Find the Package Manager UI package, and click remove.

Same with ads package

**Comment by loppitz** [comment]
Problem gelöst - musste das XR toolkit neu reinladen & die scripts neu anlegen, jetzt funktioniert wieder alles
