### ISSUE TITLE
Playerposition am Anfang passt nicht

### ISSUE THREAD

**Issue by smeerws** [4ahmns2122-VR/VRProjekt2122-LOppitz#5]
Ist höher oben als sonst

**Comment by smeerws** [comment]
![image](https://user-images.githubusercontent.com/28704310/150363322-c0a034ef-a4cc-448e-9665-a75ef7c81625.png)
Habe den zweiten Controller hingelegt, gefühlt 1m über Boden. nach ersten teleport passt es dann.

**Comment by smeerws** [comment]
![image](https://user-images.githubusercontent.com/28704310/150363548-9d99d7b8-ad3a-4887-ab97-950e25e4086c.png)

**Comment by loppitz** [comment]
ich habe die position so verändert dass sie wieder passen sollte
